Update prebuilt rule docs for 8.7
elastic/security-docs pull request #3650
Opened 2023-07-27 22:23 UTC by Mikaayenson

# Summary

Updates the docs per design in https://github.com/elastic/detection-rules/issues/2867#issuecomment-1650370453

2023-07-27 22:24 UTC, Mikaayenson commented on docs/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
> +<<suspicious-net-code-compilation>>
Same thing here. I think we should delete this file altogether right?

2023-07-27 23:30 UTC, Mikaayenson commented on docs/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
> +To see the updates for 8.8 and further releases, please visit the https://www.elastic.co/guide/en/security/8.8/prebuilt-rules-downloadable-updates.html[last version] for the updates.
```suggestion
To see the updates for 8.7 and further releases, please visit the https://www.elastic.co/guide/en/security/8.7/prebuilt-rules-downloadable-updates.html[last version] for the updates.
```
```suggestion
To see the updates for 8.8 and further releases, please visit the https://www.elastic.co/guide/en/security/8.8/prebuilt-rules-downloadable-updates.html[last version] for the updates.
```
```suggestion
To see the updates for 8.8 and further releases, please visit the https://www.elastic.co/guide/en/security/8.8/prebuilt-rules-downloadable-updates.html[last version] for the updates.
```

2023-07-28 11:23 UTC, approksiu approved these changes
Looks good!

2023-07-28 11:41 UTC, approksiu requested changes
Please keep the "prebuilt rule updates per release" page

2023-07-28 11:41 UTC, approksiu commented on docs/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
keep this page

2023-07-28 14:17 UTC, approksiu approved these changes

2023-07-28 14:48 UTC, joepeeples approved these changes

2023-07-28 15:02 UTC, merged