Updates to Entity Analytics Dashboard
elastic/security-docs pull request #4345
Opened 2023-11-30 16:34 UTC by natasha-moore-elastic

Resolves #4314.

Preview:

2023-12-01 15:42 UTC, jmikell821 reviewed
Looks great! Just one small comment. I will "approve" to not block the merging, but let's wait for @SourinPaul's approval before merging.

2023-12-01 15:42 UTC, jmikell821 commented on docs/dashboards/entity-dashboard.asciidoc
> +To display anomaly data, you must {ml-docs}/ml-ad-run-jobs.html[install and run] one or more <<prebuilt-ml-jobs, prebuilt anomaly detection jobs>>. Custom anomaly detection jobs cannot be added to th
Flip to active voice:
```suggestion
To display anomaly data, you must {ml-docs}/ml-ad-run-jobs.html[install and run] one or more <<prebuilt-ml-jobs, prebuilt anomaly detection jobs>>. You cannot add custom anomaly detection jobs to the Entity Analytics dashboard.
```

2023-12-01 15:47 UTC, jmikell821 submitted a review, later dismissed

2023-12-02 01:20 UTC, SourinPaul requested changes

2023-12-02 01:20 UTC, SourinPaul commented on docs/dashboards/entity-dashboard.asciidoc
> +To display anomaly data, you must {ml-docs}/ml-ad-run-jobs.html[install and run] one or more <<prebuilt-ml-jobs, prebuilt anomaly detection jobs>>. You cannot add custom anomaly detection jobs to the
Does it make sense to simply? 

`The Anomalies table displays the total number of host and user anomalies identified` to `The Anomalies table displays the total number of anomalies identified`

2023-12-02 01:27 UTC, SourinPaul commented on docs/dashboards/entity-dashboard.asciidoc
> +If anomaly data is missing, click the *Run job* link next to a {ml} job to install and start the job.
@ajosh0504 @machadoum, do you recall why we added this explicitly?

2023-12-05 16:43 UTC, jmikell821 submitted a review, later dismissed

2023-12-05 22:05 UTC, SourinPaul approved these changes

2023-12-05 22:05 UTC, SourinPaul commented on docs/dashboards/entity-dashboard.asciidoc
> +If anomaly data is missing, click the *Run job* link next to a {ml} job to install and start the job.
Thanks, @machadoum, for confirming.

@natasha-moore-elastic I suggest removing line 88 entirely, as it is redundant to line 82. Thanks!

2023-12-06 15:40 UTC, SourinPaul approved these changes

2023-12-06 17:08 UTC, jmikell821 approved these changes

2023-12-06 17:09 UTC, merged