Cloud security posture dashboard 8.12 updates
elastic/security-docs pull request #4530
Opened 2023-12-28 21:30 UTC by benironside

Addresses #4529 (along with serverless PR) by updating the cloud posture dashboard pages (three pages due to classic docs limitations that prevent single-sourcing). Image and text updates reflect a redesigned UI that groups monitored resources by CIS benchmark rather than highlighting compliance scores for individual accounts. This makes the dashboard more scalable for larger orgs.

Previews: 
Cloud posture dashboard pages one, two, and three

2024-01-09 00:39 UTC, tinnytintin10 requested changes
Requested some minor changes

2024-01-09 00:39 UTC, tinnytintin10 commented on docs/cloud-native-security/cspm-cloud-posture-dashboard.asciidoc
> +Below the summary section, each row shows the CSP for a benchmark that applies to your monitored cloud resources. For example, if you are monitoring GCP and Azure cloud accounts, a row appears for CI
@benironside replace GCP Azure with CIS Azure

2024-01-09 00:39 UTC, tinnytintin10 commented on docs/dashboards/cloud-posture.asciidoc
> +Below the summary section, each row shows the CSP for a benchmark that applies to your monitored cloud resources. For example, if you are monitoring GCP and Azure cloud accounts, a row appears for CI
CIS Azure instead of GCP Azure

2024-01-10 17:03 UTC, nastasha-solomon submitted a review, later dismissed
Looks great!

2024-01-10 17:03 UTC, nastasha-solomon commented on docs/cloud-native-security/kspm-cloud-posture-dashboard.asciidoc
> +* Configuration risk metrics grouped by the applicable benchmark, for example CIS GCP, CIS Azure, CIS Kubernetes, or CIS EKS
```suggestion
* Configuration risk metrics grouped by the applicable benchmark, for example, CIS GCP, CIS Azure, CIS Kubernetes, or CIS EKS
```

2024-01-10 17:03 UTC, nastasha-solomon commented on docs/dashboards/cloud-posture.asciidoc
> +* Configuration risk metrics grouped by the applicable benchmark, for example CIS GCP, CIS Azure, CIS Kubernetes, or CIS EKS
```suggestion
* Configuration risk metrics grouped by the applicable benchmark, for example, CIS GCP, CIS Azure, CIS Kubernetes, or CIS EKS
```

2024-01-10 20:22 UTC, nastasha-solomon approved these changes

2024-01-10 20:38 UTC, merged