Issue #548: 7.12.0 release notes
elastic/security-docs pull request #550
Opened 2021-03-11 17:58 UTC by nastasha-solomon

Opening draft PR for 7.12 RN.

2021-03-17 16:18 UTC, jmikell821 requested changes

2021-03-17 16:18 UTC, jmikell821 commented on docs/release-notes.asciidoc
> +* Critical threshold rule fixes ({pull}92667[#92667]).
Let's put these on one line since they are the same. 
```suggestion
* Fixes to threshold rules fixes ({pull}93553[#93553]),({pull}92667[#92667]).
* Critical threshold rule fixes .
```

2021-03-17 17:41 UTC, nastasha-solomon commented on docs/release-notes.asciidoc
> +* Critical threshold rule fixes ({pull}92667[#92667]).
Removed text in line 39 since reference PR in line 38.

2021-03-17 17:50 UTC, nastasha-solomon commented
Updated release notes available [here](https://security-docs_550.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html).

2021-03-17 21:53 UTC, spong approved these changes
Detections changes LGTM! 👍  Thanks! 🙂

2021-03-22 18:50 UTC, jmikell821 commented on docs/release-notes.asciidoc
> +
@nastasha-solomon change your ID tag to `known-issues-7.12.0` - that's why the build is failing. Also add the workaround for the pagination issue listed here: https://github.com/elastic/kibana/issues/94929#issuecomment-804212882

2021-03-22 20:07 UTC, nastasha-solomon commented
Known issue described in [this comment](https://github.com/elastic/kibana/issues/94929#issuecomment-804212882) documented and available for review.

Preview [here](https://security-docs_550.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html).

2021-03-23 13:11 UTC, jmikell821 approved these changes

2021-03-23 14:02 UTC, merged