[DOCS] Privileges Matrix for Detections Feature
elastic/security-docs pull request #634
Opened 2021-04-19 18:48 UTC by nastasha-solomon

Addresses #536 .

2021-04-29 16:35 UTC, jmikell821 requested changes
Hi @nastasha-solomon - few slight suggestions. Please also fix this grammatical error in the beginning. 
![image](https://user-images.githubusercontent.com/57149392/116586413-6e842d80-a8e7-11eb-8f04-ed236a934f57.png)

2021-04-29 16:35 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +Enabling the Detections feature allows you to view and use the Detections page from within the Security app. You only need to complete this action once and can choose between enabling it for a single
```suggestion
Enabling the Detections feature allows you to view and use the Detections page within the Security app. You only need to complete this action once and can choose between enabling it for a single Kibana space or across multiple ones. Once the Detections feature is enabled, additional privileges are needed to manage detection rules and alerts, described in the following table. 
```

2021-04-29 16:35 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +Note: Allows you to manage alerts, but not modify rules.
```suggestion
**Note:** Allows you to manage alerts, but not modify rules.
```

2021-04-29 16:35 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +         ** `.items-*` system indices.
```suggestion
         ** `.items-*`
```

2021-04-29 16:35 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +a| * The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices where <kib-space>` is the {kib} space name:
I think we can remove the first bullet. 

```suggestion
a| The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices where <kib-space>` is the {kib} space name:
```

2021-04-29 16:35 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +a| * The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices:
```suggestion
a| The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices:
```

2021-04-29 16:35 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +a| * The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the for the following system indices where <kib-space>` is the {kib} space name:
```suggestion
a| The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the for the following system indices where <kib-space>` is the {kib} space name:
```

2021-04-29 16:35 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +a| * The `maintenance`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices where <kib-space>` is the {kib} space name:
```suggestion
a| The `maintenance`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices where <kib-space>` is the {kib} space name:
```

2021-04-29 17:54 UTC, nastasha-solomon commented
@jmikell821 updates are ready for your review when you have a chance!

2021-04-29 20:36 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +Enabling the Detections feature allows you to view and use the Detections page from within the Security app. You only need to complete this action once and can choose between enabling it for a single
```suggestion
Enabling the Detections feature allows you to view and use the Detections page from within the Security app. You only need to complete this action once and can choose between enabling it for a single Kibana space or across multiple ones. Once the Detections feature is enabled, additional privileges are needed to use detection rules and alerts, described in the following table.
```

2021-04-29 20:36 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +a|The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices where <kib-space>` is the {kib} space name:
Let's make `<kib-space>` code text throughout. 

```suggestion
a|The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices where `<kib-space>` is the {kib} space name:
```

2021-04-29 20:36 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +a|The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the for the following system indices where <kib-space>` is the {kib} space name:
```suggestion
a|The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the for the following system indices where `<kib-space>` is the {kib} space name:
```

2021-04-29 20:36 UTC, jmikell821 commented on docs/getting-started/detections-req.asciidoc
> +a|The `maintenance`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices where <kib-space>` is the {kib} space name:
```suggestion
a|The `maintenance`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices where `<kib-space>` is the {kib} space name:
```

2021-04-29 21:00 UTC, jmikell821 commented
Hi @spong and @peluja1012 - please review this draft matrix privileges PR. We left the original paragraphs in the topic for now as a reference point, but will delete them before we publish. We'll be enhancing this page as Security enables feature-based permissions, but for now, please take a look and let us know if there's anything missing or incorrect. Thank you!

2021-04-29 21:05 UTC, jmikell821 approved these changes

2021-04-30 23:45 UTC, spong commented on docs/getting-started/detections-req.asciidoc
> +Enabling the Detections feature allows you to view and use the Detections page from within the Security app. You only need to complete this action once and can choose between enabling it for a single
> You only need to complete this action once and can _choose between enabling it for a single Kibana space or across multiple ones._

Not sure I'm following the distinction here?  This action will need to be completed on each space they intend to enable detections, as there is no way to bulk setup multiple spaces via the UI (can be automated via the API though). Does 'choose between enabling...' mean here to "use this role and go to each space to complete setup"?

2021-04-30 23:48 UTC, spong commented on docs/getting-started/detections-req.asciidoc
> +{kibana-ref}/xpack-spaces.html#spaces-control-user-access[Feature access based on user privileges])
Ahhh, I think I see the distinction from above. Breaking out the `per space` vs `all space` access to alerts. This makes sense to me, but just note that even with the above `all space` configuration the user will need to go to the security app of each space to complete the `setup` of the detection engine (creating the index/ILM, etc).

2021-04-30 23:51 UTC, spong approved these changes
Just one nit about the distinction between `access` and `setup` between all spaces, but other than that LGTM! Thank you so much for tackling this one and making a clean and clear matrix to determine what privileges are necessary for specific actions! This is great for our users! 🙂 🎉

2021-05-05 23:29 UTC, spong commented
Just noticed this @nastasha-solomon, but as of https://github.com/elastic/kibana/issues/90715 we don't need `Saved Objects Management`  `all` privileges anymore, so we can remove those two references from the Enable/Access Detections sections.

2021-05-17 17:32 UTC, jmikell821 commented
@nastasha-solomon here's my take on the intro para you had. Let's merge this in and see what it looks like. I'll comment out the superfluous text at the bottom afterwards. 

> To use the Detections page, the Detections feature must be enabled and your role must have access to rules and alerts. If your role does not have the cluster and index privileges needed to enable this feature, you can request someone who has these privileges to turn it on for you. The following table describes the required privileges to access the Detections page - including rules and alerts.

2021-05-18 12:43 UTC, nastasha-solomon reviewed
LGTM!

2021-05-18 16:20 UTC, jmikell821 commented
Hi @spong, @peluja1012 and @FrankHassanabad - would appreciate your review/feedback of this topic that's been heavily revised and reorganized. Please confirm everything is accurate and if you have any further suggestions. 

We'll be updating this topic regularly to coordinate with the new RBAC permissions. Thank you!

2021-05-18 23:31 UTC, spong commented on docs/getting-started/detections-req.asciidoc
> +To use the Detections page, the Detections feature must be enabled and your role must have access to rules and alerts. If your role does not have the cluster and index privileges needed to enable thi
Similar to my previous comment below, I think it's worth explicitly calling out that it's not just these privileges that are necessary to enable the Detections feature, but also that the user with the specified privileges _must visit the Security Application at least once_ for each space they'd like to enable the feature. We've had some [discuss posts](https://discuss.elastic.co/t/cant-access-detections-from-a-different-space/272118/9) where this aspect of the configuration wasn't entirely clear, so would be worth highlighting in a tip/info callout.

2021-05-24 20:36 UTC, spong approved these changes
Latest changes LGTM! Thanks for all the effort here @nastasha-solomon and @jmikell821! 🙂

2021-05-25 13:31 UTC, merged