[DOCS] 7.14.1 Release Notes
elastic/security-docs pull request #987
Opened 2021-08-24 21:27 UTC by nastasha-solomon

Addresses #969.

Preview here.

2021-08-30 02:58 UTC, jmikell821 commented on docs/release-notes.asciidoc
> +The `securitySolution:defaultThreatIndex` advanced setting allows you to specify one or more threat intelligence index from which {es-sec} will collect threat match data. It controls features that qu
```suggestion
The `securitySolution:defaultThreatIndex` advanced setting allows you to specify one or more threat intelligence indices from which {elastic-sec} will collect threat match data. It controls features that query threat indices, such as the Threat Intelligence view on the Overview page, and uses the `filebeat-*` index by default.
```

2021-08-30 02:59 UTC, jmikell821 commented on docs/release-notes.asciidoc
> +* Fixes UI errors that were caused by the rule `author` field not being migrated. ({pull}107230[#107230]).
```suggestion
* Fixes UI errors that were caused by the rule `author` field not being migrated ({pull}107230[#107230]).
```

2021-08-30 03:01 UTC, jmikell821 reviewed
A few small nits, then OK to merge to `7.x`, then backport to `7.14` and `7.15`. If you run into any issues, contact Lisa.

2021-08-30 18:24 UTC, rylnd requested changes
I think we just need a better description for the setting (#993) , and then this'll be good to go.

2021-08-30 18:24 UTC, rylnd commented on docs/release-notes.asciidoc
> +You can enable cross cluster search by adding threat indices from remote clusters. Filebeat indices are supported. Non-Filebeat indices require ECS-compliant threat field mappings to ensure threat ma
Same note here as in #993 ; the `Filebeat indices are supported.` sentence raises more questions than it answers, IMO.

2021-08-31 21:54 UTC, ecezalp approved these changes
LGTM, adding some minor comments

> The setting controls features that query threat indices

I think we can say `configures` instead of `controls`

> such as the Threat Intelligence view on the Overview page and threat indicator match rules.

I think we can say `the Threat Intelligence view on the Overview page and the default indicator index values for indicator match rules.`

2021-09-01 00:01 UTC, merged